name: Build Example Decoder

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    name: Compile SimpleDecode
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.2

      - name: Install AVR Core
        run: arduino-cli core update-index && arduino-cli core install arduino:avr

      - name: Compile SimpleDecode
        run: |
          arduino-cli compile --fqbn arduino:avr:uno \
            --library ./MfxDecoder \
            ./MfxDecoder/examples/SimpleDecode/SimpleDecode.ino
